/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boulangerie;

import javax.swing.JFrame;

/**
 *
 * @author Khalil_joop
 */
public class Formulaire extends javax.swing.JFrame {

    /**
     * Creates new form Formulaire
     */
    public Formulaire() {
        initComponents();
       // setResizable(false); 
         // centre la fenêtre
    setLocationRelativeTo(null);
    // aucune action sur la fermeture (comme il n'y a plus de boutons....)
    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); 
         pane_centre.removeAll();
        pane_centre.add(pane_accueil);
        pane_centre.repaint();
        pane_centre.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pane_parent = new javax.swing.JPanel();
        pane_header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pane_menu = new javax.swing.JPanel();
        btn_addFournisseur = new javax.swing.JButton();
        btn_menu_addClient = new javax.swing.JButton();
        btn_accueil = new javax.swing.JButton();
        btn_menu_add_cmd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pane_centre = new javax.swing.JPanel();
        pane_addFournisseur = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pane_commande = new javax.swing.JPanel();
        pane_addCmd = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        select_client_cmd = new javax.swing.JComboBox<>();
        select_type_pain_cmd = new javax.swing.JComboBox<>();
        zone_nbre_cmd = new javax.swing.JTextField();
        btn_add_cmd = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        pane_content_tabCmd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_add_cmd = new javax.swing.JTable();
        btn_valide_cmd = new javax.swing.JButton();
        pane_addClient = new javax.swing.JPanel();
        pane_add_client = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        zone_prenom_client = new javax.swing.JTextField();
        zone_nom_client = new javax.swing.JTextField();
        zone_addresse_client = new javax.swing.JTextField();
        zone_phone_client = new javax.swing.JTextField();
        btn_addClient = new javax.swing.JButton();
        pane_content_tabClient = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_add_client = new javax.swing.JTable();
        btn_valider_tabClient = new javax.swing.JButton();
        pane_accueil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_add = new javax.swing.JMenu();
        nw = new javax.swing.JMenu();
        menu_add_client = new javax.swing.JMenuItem();
        menu_add_fourn = new javax.swing.JMenuItem();
        menu_close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pane_header.setBackground(new java.awt.Color(0, 255, 204));
        pane_header.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+34));
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Boulangerie ");

        jLabel13.setFont(jLabel13.getFont().deriveFont((jLabel13.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabel13.getFont().getSize()+22));
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Serigne Mbacke Seck");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OIP2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel12.setBackground(new java.awt.Color(0, 255, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/th.jpg"))); // NOI18N

        javax.swing.GroupLayout pane_headerLayout = new javax.swing.GroupLayout(pane_header);
        pane_header.setLayout(pane_headerLayout);
        pane_headerLayout.setHorizontalGroup(
            pane_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_headerLayout.createSequentialGroup()
                .addGroup(pane_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pane_headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(58, 58, 58)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pane_headerLayout.setVerticalGroup(
            pane_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_headerLayout.createSequentialGroup()
                .addGroup(pane_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pane_headerLayout.createSequentialGroup()
                        .addGroup(pane_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pane_headerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_menu.setBackground(new java.awt.Color(102, 51, 255));
        pane_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_addFournisseur.setText("Fournisseur");
        btn_addFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addFournisseurActionPerformed(evt);
            }
        });

        btn_menu_addClient.setText("Clent");
        btn_menu_addClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_addClientActionPerformed(evt);
            }
        });

        btn_accueil.setText("Accueil");
        btn_accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accueilActionPerformed(evt);
            }
        });

        btn_menu_add_cmd.setText("Ajouter Commande");
        btn_menu_add_cmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_add_cmdActionPerformed(evt);
            }
        });

        jButton1.setText("Liste Commandes");

        javax.swing.GroupLayout pane_menuLayout = new javax.swing.GroupLayout(pane_menu);
        pane_menu.setLayout(pane_menuLayout);
        pane_menuLayout.setHorizontalGroup(
            pane_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_menuLayout.createSequentialGroup()
                .addGroup(pane_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_menu_add_cmd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(btn_addFournisseur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_accueil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_menu_addClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pane_menuLayout.setVerticalGroup(
            pane_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_menuLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btn_accueil)
                .addGap(48, 48, 48)
                .addComponent(btn_addFournisseur)
                .addGap(45, 45, 45)
                .addComponent(btn_menu_add_cmd)
                .addGap(38, 38, 38)
                .addComponent(btn_menu_addClient)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_centre.setBackground(new java.awt.Color(255, 51, 255));
        pane_centre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pane_centre.setLayout(new java.awt.CardLayout());

        pane_addFournisseur.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setText("Fournisseur");

        javax.swing.GroupLayout pane_addFournisseurLayout = new javax.swing.GroupLayout(pane_addFournisseur);
        pane_addFournisseur.setLayout(pane_addFournisseurLayout);
        pane_addFournisseurLayout.setHorizontalGroup(
            pane_addFournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_addFournisseurLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pane_addFournisseurLayout.setVerticalGroup(
            pane_addFournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_addFournisseurLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel3)
                .addContainerGap(1178, Short.MAX_VALUE))
        );

        pane_centre.add(pane_addFournisseur, "card4");

        pane_commande.setBackground(new java.awt.Color(255, 255, 204));

        pane_addCmd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Client");

        jLabel6.setText("Type de pain");

        jLabel7.setText("nombre");

        select_client_cmd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        select_type_pain_cmd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_add_cmd.setText("Ajouter");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Nouvelle Commande");

        javax.swing.GroupLayout pane_addCmdLayout = new javax.swing.GroupLayout(pane_addCmd);
        pane_addCmd.setLayout(pane_addCmdLayout);
        pane_addCmdLayout.setHorizontalGroup(
            pane_addCmdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_addCmdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_addCmdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(pane_addCmdLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(pane_addCmdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zone_nbre_cmd)
                    .addComponent(select_type_pain_cmd, 0, 164, Short.MAX_VALUE)
                    .addComponent(select_client_cmd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_addCmdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_add_cmd)
                .addGap(29, 29, 29))
            .addGroup(pane_addCmdLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pane_addCmdLayout.setVerticalGroup(
            pane_addCmdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_addCmdLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(pane_addCmdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(select_client_cmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(61, 61, 61)
                .addGroup(pane_addCmdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_type_pain_cmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(57, 57, 57)
                .addGroup(pane_addCmdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zone_nbre_cmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(64, 64, 64)
                .addComponent(btn_add_cmd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_add_cmd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Client", "Type pain", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_add_cmd);

        btn_valide_cmd.setText("Valider");

        javax.swing.GroupLayout pane_content_tabCmdLayout = new javax.swing.GroupLayout(pane_content_tabCmd);
        pane_content_tabCmd.setLayout(pane_content_tabCmdLayout);
        pane_content_tabCmdLayout.setHorizontalGroup(
            pane_content_tabCmdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_content_tabCmdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_valide_cmd)
                .addGap(68, 68, 68))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        pane_content_tabCmdLayout.setVerticalGroup(
            pane_content_tabCmdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_content_tabCmdLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btn_valide_cmd)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout pane_commandeLayout = new javax.swing.GroupLayout(pane_commande);
        pane_commande.setLayout(pane_commandeLayout);
        pane_commandeLayout.setHorizontalGroup(
            pane_commandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_commandeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pane_addCmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pane_content_tabCmd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pane_commandeLayout.setVerticalGroup(
            pane_commandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_commandeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_commandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane_addCmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pane_content_tabCmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pane_centre.add(pane_commande, "card5");

        pane_add_client.setBackground(new java.awt.Color(255, 255, 255));
        pane_add_client.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Prenom");

        jLabel9.setText("Nom");

        jLabel10.setText("Adresse");

        jLabel11.setText("Telephone");

        btn_addClient.setText("Ajouter");
        btn_addClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_add_clientLayout = new javax.swing.GroupLayout(pane_add_client);
        pane_add_client.setLayout(pane_add_clientLayout);
        pane_add_clientLayout.setHorizontalGroup(
            pane_add_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_add_clientLayout.createSequentialGroup()
                .addGroup(pane_add_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pane_add_clientLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_addClient, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pane_add_clientLayout.createSequentialGroup()
                        .addGroup(pane_add_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pane_add_clientLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(pane_add_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(pane_add_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8))))
                            .addGroup(pane_add_clientLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addGap(110, 110, 110)
                        .addGroup(pane_add_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(zone_prenom_client, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(zone_nom_client, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zone_addresse_client, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zone_phone_client))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        pane_add_clientLayout.setVerticalGroup(
            pane_add_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_add_clientLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pane_add_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(zone_prenom_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(pane_add_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(zone_nom_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pane_add_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_add_clientLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel10))
                    .addGroup(pane_add_clientLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(zone_addresse_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(pane_add_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(zone_phone_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btn_addClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_content_tabClient.setBackground(new java.awt.Color(255, 255, 255));
        pane_content_tabClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tab_add_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "prenom", "Nom", "Adresse", "Telephone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tab_add_client);

        btn_valider_tabClient.setText("Valider");

        javax.swing.GroupLayout pane_content_tabClientLayout = new javax.swing.GroupLayout(pane_content_tabClient);
        pane_content_tabClient.setLayout(pane_content_tabClientLayout);
        pane_content_tabClientLayout.setHorizontalGroup(
            pane_content_tabClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_content_tabClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_content_tabClientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_valider_tabClient)
                .addGap(179, 179, 179))
        );
        pane_content_tabClientLayout.setVerticalGroup(
            pane_content_tabClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_content_tabClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btn_valider_tabClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pane_addClientLayout = new javax.swing.GroupLayout(pane_addClient);
        pane_addClient.setLayout(pane_addClientLayout);
        pane_addClientLayout.setHorizontalGroup(
            pane_addClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_addClientLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pane_add_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pane_content_tabClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pane_addClientLayout.setVerticalGroup(
            pane_addClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_addClientLayout.createSequentialGroup()
                .addGroup(pane_addClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_content_tabClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pane_add_client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 865, Short.MAX_VALUE))
        );

        pane_centre.add(pane_addClient, "card3");

        pane_accueil.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setText("Accueil");

        javax.swing.GroupLayout pane_accueilLayout = new javax.swing.GroupLayout(pane_accueil);
        pane_accueil.setLayout(pane_accueilLayout);
        pane_accueilLayout.setHorizontalGroup(
            pane_accueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_accueilLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(926, Short.MAX_VALUE))
        );
        pane_accueilLayout.setVerticalGroup(
            pane_accueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_accueilLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addContainerGap(1176, Short.MAX_VALUE))
        );

        pane_centre.add(pane_accueil, "card2");

        javax.swing.GroupLayout Pane_parentLayout = new javax.swing.GroupLayout(Pane_parent);
        Pane_parent.setLayout(Pane_parentLayout);
        Pane_parentLayout.setHorizontalGroup(
            Pane_parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pane_parentLayout.createSequentialGroup()
                .addGroup(Pane_parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pane_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Pane_parentLayout.createSequentialGroup()
                        .addComponent(pane_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pane_centre, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Pane_parentLayout.setVerticalGroup(
            Pane_parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pane_parentLayout.createSequentialGroup()
                .addComponent(pane_header, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pane_parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane_centre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pane_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menu_add.setText("File");

        nw.setText("Ajouter");

        menu_add_client.setText("Client");
        menu_add_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_add_clientActionPerformed(evt);
            }
        });
        nw.add(menu_add_client);

        menu_add_fourn.setText("Fournisseur");
        nw.add(menu_add_fourn);

        menu_close.setText("Fermer");
        menu_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_closeActionPerformed(evt);
            }
        });
        nw.add(menu_close);

        menu_add.add(nw);

        jMenuBar1.add(menu_add);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane_parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane_parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_accueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accueilActionPerformed
        // TODO add your handling code here:
        pane_centre.removeAll();
        pane_centre.add(pane_accueil);
        pane_centre.repaint();
        pane_centre.revalidate();
    }//GEN-LAST:event_btn_accueilActionPerformed

    private void btn_addFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addFournisseurActionPerformed
        // TODO add your handling code here:
         pane_centre.removeAll();
        pane_centre.add(pane_addFournisseur);
        pane_centre.repaint();
        pane_centre.revalidate();
    }//GEN-LAST:event_btn_addFournisseurActionPerformed

    private void btn_menu_addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_addClientActionPerformed
        // TODO add your handling code here:
         pane_centre.removeAll();
        pane_centre.add(pane_addClient);
        pane_centre.repaint();
        pane_centre.revalidate();
    }//GEN-LAST:event_btn_menu_addClientActionPerformed

    private void btn_menu_add_cmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_add_cmdActionPerformed
        // TODO add your handling code here:
         pane_centre.removeAll();
        pane_centre.add(pane_commande);
        pane_centre.repaint();
        pane_centre.revalidate();
    }//GEN-LAST:event_btn_menu_add_cmdActionPerformed

    private void btn_addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addClientActionPerformed

    private void menu_add_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_add_clientActionPerformed
        // TODO add your handling code here:
         pane_centre.removeAll();
        pane_centre.add(pane_addClient);
        pane_centre.repaint();
        pane_centre.revalidate();
    }//GEN-LAST:event_menu_add_clientActionPerformed

    private void menu_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_closeActionPerformed
        // TODO add your handling code here:
        //Formulaire f=new Formulaire();
        System.exit(0);
    }//GEN-LAST:event_menu_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pane_parent;
    private javax.swing.JButton btn_accueil;
    private javax.swing.JButton btn_addClient;
    private javax.swing.JButton btn_addFournisseur;
    private javax.swing.JButton btn_add_cmd;
    private javax.swing.JButton btn_menu_addClient;
    private javax.swing.JButton btn_menu_add_cmd;
    private javax.swing.JButton btn_valide_cmd;
    private javax.swing.JButton btn_valider_tabClient;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menu_add;
    private javax.swing.JMenuItem menu_add_client;
    private javax.swing.JMenuItem menu_add_fourn;
    private javax.swing.JMenuItem menu_close;
    private javax.swing.JMenu nw;
    private javax.swing.JPanel pane_accueil;
    private javax.swing.JPanel pane_addClient;
    private javax.swing.JPanel pane_addCmd;
    private javax.swing.JPanel pane_addFournisseur;
    private javax.swing.JPanel pane_add_client;
    private javax.swing.JPanel pane_centre;
    private javax.swing.JPanel pane_commande;
    private javax.swing.JPanel pane_content_tabClient;
    private javax.swing.JPanel pane_content_tabCmd;
    private javax.swing.JPanel pane_header;
    private javax.swing.JPanel pane_menu;
    private javax.swing.JComboBox<String> select_client_cmd;
    private javax.swing.JComboBox<String> select_type_pain_cmd;
    private javax.swing.JTable tab_add_client;
    private javax.swing.JTable tab_add_cmd;
    private javax.swing.JTextField zone_addresse_client;
    private javax.swing.JTextField zone_nbre_cmd;
    private javax.swing.JTextField zone_nom_client;
    private javax.swing.JTextField zone_phone_client;
    private javax.swing.JTextField zone_prenom_client;
    // End of variables declaration//GEN-END:variables
}
